### ISSUE TITLE
Keywords from Dancer2::Plugin::Ajax not imported

### ISSUE THREAD

**Issue by mrmaloof** [preaction/Import-Base#27]
I'm not sure if this is an issue with Dancer2::Plugins:: or with Import::Base.

This works as I expect.
```perl
use Test::More;
use Dancer2;
use Dancer2::Plugin::Ajax;

can_ok( __PACKAGE__, 'dancer_version' );
can_ok( __PACKAGE__, 'ajax' );
done_testing();
```
While this does not.
```perl
use Test::More;

package MyBase {
    use base 'Import::Base';
    our @IMPORT_MODULES = ( 'Dancer2', 'Dancer2::Plugin::Ajax' );
}

package main {
    MyBase->import();
    can_ok( __PACKAGE__, 'dancer_version' );
    can_ok( __PACKAGE__, 'ajax' );
}
done_testing();
```

**Comment by preaction** [comment]
This looks to be a limitation in Dancer/Dancer2's register_plugin sub: If the parent caller, the one loading the module, doesn't have Dancer2 already loaded and imported when loading the plugin (not importing, just loading), the plugin does not register itself with the DSL, and its registered subs don't get exported. I'm asking #dancer on irc.perl.org about it right now, since it doesn't work with `import::into` either.

**Comment by preaction** [comment]
I lied, it works fine with Import::Into as long as it happens at compile time. The issue seems to be that Import::Base uses Module::Runtime `use_module`, which then makes the Dancer2::Plugin think that `require_module` is its caller, which is absurd.

Likely, Dancer2::Plugin should walk up the call stack and search every package for a `dsl` method to register itself on, though I have no idea of the ramifications of that...
