### ISSUE TITLE
@IMPORT_MODULES don't have to be changed to get Exporter mechanics

### ISSUE THREAD

**Issue by kentfredric** [preaction/Import-Base#32]
```perl
use strict;
use warnings;

BEGIN {
  package My::A; 

  $INC{'My/A.pm'} = 1;
  use parent 'Import::Base';

  our @IMPORT_MODULES = (
    'strict',
    'warnings',
     #note: no self reference
  );

  our @EXPORT_OK = ('foo');
  sub foo {
    print "Hello";
  }
}

BEGIN {
  package My::B;

  $INC{'My/B.pm'} = 1;
  use parent 'Import::Base';

  our @IMPORT_MODULES = (
    'My::A' => [ 'foo' ],   # should be illegal, but gets Exporter
  );

}

BEGIN {
  package My::C;

  use My::B;

    foo(); # trampolined into existence.
}
```

**Comment by kentfredric** [comment]
Also, with 

```perl
@My::A::EXPORT = qw( foo );

@My::B::IMPORT_MODULES = qw( My::A );
```
My::C will also get `foo`

This could be seen as a feature given our recent conversation.

**Comment by preaction** [comment]
Hmm... yeah... I could totally see both of these things being both features and bugs... I'm partially-inclined to say if you don't want it exported, keep it away from `@EXPORT` and `@EXPORT_OK`...

**Comment by preaction** [comment]
I think with #30 and clear documentation that a consumer can import bundles and subs from the base module, this would become expected behavior. I do feel a bit unnerved by the potential for interaction between the two things, though, so we'll likely have to be wary for a bit. But, for now, this is rolled in to #30
